/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.iespuertodelacruz.ymp.view;

/**
 *
 * @author Yared
 */
public class JdialogReserva extends javax.swing.JDialog {

    /**
     * Creates new form JdialogReserva
     */
    public JdialogReserva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        btnReservar = new javax.swing.JButton();
        chTipo = new javax.swing.JComboBox<>();
        lblNumeroPersonas = new javax.swing.JLabel();
        txfNumero = new javax.swing.JTextField();
        lblTipoCocina = new javax.swing.JLabel();
        chCocina = new javax.swing.JComboBox<>();
        lblNumeroJornadas = new javax.swing.JLabel();
        txfNumeroJornadas = new javax.swing.JTextField();
        cbHabitaciones = new javax.swing.JCheckBox();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        txfApellidos = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblNumeroHabitaciones = new javax.swing.JLabel();
        SpinFecha = new javax.swing.JSpinner();
        txfNumeroHabitaciones = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTipo.setText("Tipo de evento");
        lblTipo.setToolTipText("Elije el tipo del evento");

        btnReservar.setText("Reservar");
        btnReservar.setToolTipText("Realizar la reserva de la sala");

        chTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        chTipo.setToolTipText("Elije el tipo de evento");
        chTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chTipoActionPerformed(evt);
            }
        });

        lblNumeroPersonas.setText("Número de personas");
        lblNumeroPersonas.setToolTipText("Introduce la cantidad de personas que asistirán");

        txfNumero.setToolTipText("Introduce la cantidad de personas");

        lblTipoCocina.setText("Tipo de cocina");
        lblTipoCocina.setToolTipText("Elige el tipo de cocina");

        chCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bufé", "Carta", "Pedir cita con el chef", "No precisa" }));
        chCocina.setToolTipText("Elije el tipo de cocina");
        chCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chCocinaActionPerformed(evt);
            }
        });

        lblNumeroJornadas.setText("Número de jornadas");
        lblNumeroJornadas.setToolTipText("Introduce el número de jornadas del congreso");
        lblNumeroJornadas.setEnabled(false);

        txfNumeroJornadas.setToolTipText("Introduce le número de jornadas del congreso");
        txfNumeroJornadas.setEnabled(false);
        txfNumeroJornadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumeroJornadasActionPerformed(evt);
            }
        });

        cbHabitaciones.setText("Habitaciones para los asistentes");
        cbHabitaciones.setToolTipText("¿Se requiere habitaciones para los asistentes del congreso?");
        cbHabitaciones.setEnabled(false);
        cbHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHabitacionesActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");
        lblNombre.setToolTipText("Introduce el nombre de la persona que realiza la reserva");

        lblApellidos.setText("Teléfono");
        lblApellidos.setToolTipText("Introduce los apellidos de la persona");

        txfNombre.setToolTipText("Introduce el nombre de la persona que realiza la reserva");
        txfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreActionPerformed(evt);
            }
        });

        txfApellidos.setToolTipText("Introduce los apellidos de la persona");
        txfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfApellidosActionPerformed(evt);
            }
        });

        lblFecha.setText("Fecha Reserva");
        lblFecha.setToolTipText("Elije la fecha de la reserva");

        lblNumeroHabitaciones.setText("Número de Habitaciones");
        lblNumeroHabitaciones.setToolTipText("Introduce el número de habitaciones");
        lblNumeroHabitaciones.setEnabled(false);

        SpinFecha.setModel(new javax.swing.SpinnerDateModel());
        SpinFecha.setToolTipText("Elije la fecha de la reserva");

        txfNumeroHabitaciones.setToolTipText("Introduce el número de habitaciones");
        txfNumeroHabitaciones.setEnabled(false);
        txfNumeroHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNumeroHabitacionesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Asana Math", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Salón Habana");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 12)); // NOI18N
        jLabel2.setText("BK Hotels®");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txfNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(lblNumeroHabitaciones)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNumeroJornadas)
                                .addGap(74, 74, 74)
                                .addComponent(cbHabitaciones)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txfNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblNombre))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblTipo)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addComponent(lblApellidos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(txfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblNumeroPersonas)
                                        .addGap(1, 1, 1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(chTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SpinFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblFecha))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(lblTipoCocina))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(chCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(btnReservar)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidos)
                    .addComponent(lblFecha))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblNumeroPersonas)
                    .addComponent(lblTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNumeroJornadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroHabitaciones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReservar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chTipoActionPerformed

    private void txfNumeroJornadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumeroJornadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumeroJornadasActionPerformed

    private void cbHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHabitacionesActionPerformed

    private void txfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreActionPerformed

    private void txfNumeroHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNumeroHabitacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNumeroHabitacionesActionPerformed

    private void txfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfApellidosActionPerformed

    private void chCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chCocinaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JSpinner SpinFecha;
    public javax.swing.JButton btnReservar;
    public javax.swing.JCheckBox cbHabitaciones;
    public javax.swing.JComboBox<String> chCocina;
    public javax.swing.JComboBox<String> chTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblNumeroHabitaciones;
    public javax.swing.JLabel lblNumeroJornadas;
    private javax.swing.JLabel lblNumeroPersonas;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoCocina;
    public javax.swing.JTextField txfApellidos;
    public javax.swing.JTextField txfNombre;
    public javax.swing.JTextField txfNumero;
    public javax.swing.JTextField txfNumeroHabitaciones;
    public javax.swing.JTextField txfNumeroJornadas;
    // End of variables declaration//GEN-END:variables
}
